//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Otomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masalar_TBL
    {
        public int Masa_id { get; set; }
        public Nullable<bool> Masa_Durum { get; set; }
    }
}
