//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Otomasyonu.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cafe_OtomasyonuEntities2 : DbContext
    {
        public Cafe_OtomasyonuEntities2()
            : base("name=Cafe_OtomasyonuEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategoriler_TBL> Kategoriler_TBL { get; set; }
        public virtual DbSet<Login_TBL> Login_TBL { get; set; }
        public virtual DbSet<Masalar_TBL> Masalar_TBL { get; set; }
        public virtual DbSet<Personel_TBL> Personel_TBL { get; set; }
        public virtual DbSet<Siparisler_TBL> Siparisler_TBL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urunler_TBL> Urunler_TBL { get; set; }
    }
}
