//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Otomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel_TBL
    {
        public int Per_ID { get; set; }
        public string Per_Ad { get; set; }
        public string Per_Soyad { get; set; }
        public string Per_Telefon { get; set; }
        public string Per_Bölüm { get; set; }
    }
}
