//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_Otomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler_TBL
    {
        public int Siparis_ID { get; set; }
        public Nullable<int> Siparis_Urun { get; set; }
        public string Siparis_isim { get; set; }
        public string Siparis_Adet { get; set; }
        public Nullable<System.DateTime> Siparis_Zaman { get; set; }
        public Nullable<int> Siparis_Masa { get; set; }
        public string Siparis_Durum { get; set; }
        public Nullable<int> Siparis_Fiyat { get; set; }
    
        public virtual Urunler_TBL Urunler_TBL { get; set; }
    }
}
